### ISSUE TITLE
ocaml setup.ml -install fails to use destdir, since 0.4.8

### ISSUE THREAD

**Issue by olafhering** [ocaml/oasis#107]
Up to 0.4.7 --destdir installed the oasis binary properly. This fails with 0.4.8 and later:

```
[    1s] + ocaml setup.ml -configure --psdir /usr/share/doc/ocaml/ocaml-oasis --pdfdir /usr/share/doc/ocaml/ocaml-oasis --dvidir /usr/share/doc/ocaml/ocaml-oasis --htmldir /usr/share/doc/ocaml/ocaml-oasis --docdir /usr/share/doc/ocaml/ocaml-oasis --localedir /usr/share/locale --datadir /usr/share --bindir /usr/bin --mandir /usr/share/man --destdir /home/abuild/rpmbuild/BUILDROOT/ocaml-oasis-0.4.9.20170426.a236ff4-170517152746.0.x86_64 --datarootdir /usr/share --infodir /usr/share/info --libdir /usr/lib64 --libexecdir /usr/lib --localstatedir /var --sbindir /usr/sbin --prefix /usr --sysconfdir /etc --exec-prefix /usr --sharedstatedir /usr/com --enable-docs
...
[   29s] cp: cannot create regular file '/usr/bin/oasis': Permission denied
[   29s] E: Failure("Command ''cp' '/home/abuild/rpmbuild/BUILD/oasis-0.4.9.20170426.a236ff4/_build/src/cli/Main.native' '/usr/bin/oasis'' terminated with error code 1")

```

**Comment by gildor478** [comment]
Got exactly the same problem. Will fix it tonight.

**Comment by olafhering** [comment]
Unfortunately this does not help. 0.4.9 fails to install. Oddly only the oasis binary is affected, the libs go to destdir:

[https://build.opensuse.org/package/show/home:olh:ocaml/ocaml-oasis](url)

**Comment by gildor478** [comment]
Because oasis 0.4.9 has been generated by oasis 0.4.8.

**Comment by gildor478** [comment]
Can you try this archive to install OASIS?

The setup.ml has been generated with the same version has the one shipped in the archive. It should allow catching errors earlier.

[oasis-0.4.10~HEAD.tar.gz](https://github.com/ocaml/oasis/files/1017390/oasis-0.4.10.HEAD.tar.gz)

**Comment by olafhering** [comment]
Thanks, this archive helps.

**Comment by gildor478** [comment]
I will do an official release tonight and close the bug.

**Comment by gildor478** [comment]
OASIS 0.4.10 released:
https://forge.ocamlcore.org/frs/download.php/1694/oasis-0.4.10.tar.gz

**Comment by olafhering** [comment]
well, my oasis-0.4.9.20170523.2e34867 rpm package worked fine in the last months. Today I switched to the 0.4.10 tag (oasis-0.4.10.20170522.420dbd3 is the result) and the failure is back.

**Comment by gildor478** [comment]
Where is the package?
Can you point me to your source and build script?
Can you point me to the logs of your build attempt as well?

**Comment by olafhering** [comment]
It seems the tag 0.4.10 (420dbd3) does not match the release.
The actual release [http://forge.ocamlcore.org/frs/download.php/1694/oasis-0.4.10.tar.gz](http://forge.ocamlcore.org/frs/download.php/1694/oasis-0.4.10.tar.gz) is closer to 2e34867, which is what I used in the last months.
