### ISSUE TITLE
External commands (like ocamlbuild) are printing errors on stdout instead of stderr

### ISSUE THREAD

**Issue by maelvalais** [ocaml/oasis#111]
Dear Oasis team,

I was trying to write a little parser that would underline in red in Vim the errors returned by the output of `make` on a project relying on `oasis`.

But I found out that `ocaml setup.ml -build` redirects any errors sent to stderr by external commands (e.g., ocamlbuild) to stdout. Which is... unexpected. Why does `setup.ml` have this behavior?

Thanks!

**Comment by gildor478** [comment]
OASIS doesn't redirect STDERR to STDOUT.

Here is mytest :
```
$ cat ~/bin/ocamlbuild 
#!/bin/bash

echo "This is an error" >&2
/home/gildor/.opam/4.04.0/bin/ocamlbuild "$@"

# In oasis source directory
$ make distclean
[...]
$ ocaml setup.ml -build 2> >(while read line; do echo -e "STDERR: $line" >&2; done)
STDERR: This is an error
Finished, 1 target (0 cached) in 00:00:00.
SANITIZE: a total of 1 file that should probably not be in your source tree
[...]
+ /home/gildor/.opam/4.04.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -I src/oasis -package unix -I src/base -I src/oasis -o src/base/BaseEnv.cmo src/base/BaseEnv.ml
File "src/base/BaseEnv.ml", line 61, characters 10-21:
Error: This function has type unit -> PropList.Data.t
       It is applied to too many arguments; maybe you forgot a `;'.
Command exited with code 2.
Compilation unsuccessful after building 363 targets (0 cached) in 00:00:04.
STDERR: E: Failure("Command ''/home/gildor/bin/ocamlbuild' [...] terminated with error code 10")
```

I used a bash redirection + read loop to mark STDERR entries with STDERR prefix. It turns out to work perfectly for anything printed on STDERR in the ~/bin/ocamlbuild bash script (see "STDERR: This is an error", coming from the 3rd line of the script).

I suppose that the problem comes from ocamlbuild itself.
