### ISSUE TITLE
DllPath does not respect variable substitution

### ISSUE THREAD

**Issue by thisiscam** [ocaml/oasis#124]
I'm trying to use DllPath to link a .so shared library (specifically z3) that ships with opam. The library is located at ~/.opam/version/lib/z3, which is the path $(ocamlfind query z3).

So I wrote

```
Executable "foo"
  ...
  BuildDepends:
    z3
  DllPath: $(pkg_z3)
```

The above doesn't work, but works if I hard code the path manually. 
I found pkg_z3 is correctly defined in setup.data
I also inspected the command ocamlbuild is using using "ByteOpt: -verbose", and I got

`+ ocamlc.opt -g -dllpath ${pkg_z3} -verbose ...
`

So the variable is not expanded correctly?

**Comment by gildor478** [comment]
You should not have to use "-dllpath". This is a problem related to the z3 library. It should install its .so library in $SOMEWHERE/stublibs and have this in ld.conf file or CAML_LD_LIBRARY_PATH.

An example with a standard Debian install:
```shell
$ find /usr/lib/ocaml/ -name *.so
usr/lib/ocaml/stublibs/dllgraphics.so
/usr/lib/ocaml/stublibs/dllvmthreads.so
/usr/lib/ocaml/stublibs/dllplplot_stubs.so
/usr/lib/ocaml/stublibs/dllnetaccel_c.so
/usr/lib/ocaml/stublibs/dllsha256.so
/usr/lib/ocaml/stublibs/dllnetsys.so
[...]
/usr/lib/ocaml/stublibs/dllcryptokit_stubs.so
/usr/lib/ocaml/stublibs/dllcurl-helper.so
/usr/lib/ocaml/stublibs/dllsha1.so
/usr/lib/ocaml/stublibs/dllthreads.so
/usr/lib/ocaml/stublibs/dllnums.so
/usr/lib/ocaml/stublibs/dllrpc_auth_local.so
```
(you can see that cryptokit/plplot and other package are installing their libraries in .../stublibs)

An alternative with a local installation, like OPAM, will be to install them in .../stublibs:
```shell
$ find /home/gildor/.opam/4.04.0/lib/ -name *.so
/home/gildor/.opam/4.04.0/lib/stublibs/dllcamlzip.so
/home/gildor/.opam/4.04.0/lib/stublibs/dllpcre_stubs.so
/home/gildor/.opam/4.04.0/lib/stublibs/dllsqlite3_stubs.so
/home/gildor/.opam/4.04.0/lib/stublibs/dlllwt_unix_stubs.so
/home/gildor/.opam/4.04.0/lib/stublibs/dllbase_stubs.so
/home/gildor/.opam/4.04.0/lib/ocaml/stublibs/dllgraphics.so
/home/gildor/.opam/4.04.0/lib/ocaml/stublibs/dllunix.so
/home/gildor/.opam/4.04.0/lib/ocaml/stublibs/dllbigarray.so
/home/gildor/.opam/4.04.0/lib/ocaml/stublibs/dllthreads.so
/home/gildor/.opam/4.04.0/lib/ocaml/stublibs/dllnums.so
/home/gildor/.opam/4.04.0/lib/ocaml/stublibs/dllcamlstr.so
/home/gildor/.opam/4.04.0/lib/ocaml/stublibs/dllvmthreads.so
/home/gildor/.opam/4.04.0/lib/ocaml/libasmrun_shared.so
/home/gildor/.opam/4.04.0/lib/ocaml/libcamlrun_shared.so
```

and then override CAML_LD_LIBRARY_PATH:
```shell
CAML_LD_LIBRARY_PATH=/home/gildor/.opam/4.04.0/lib/stublibs:/home/gildor/.opam/4.04.0/lib/ocaml/stublibs
```


I don't think you should use DllPath for that -- other people with other build system will have exactly the same problem. Consider reporting a bug to either z3 or opam-repository, explaining that the z3 library is not installed at the right location.

To solve your immediate problem, just override your own CAML_LD_LIBRARY_PATH, adding the z3 path.
```shell
$ export CAML_LD_LIBRARY_PATH="${CAML_LD_LIBRARY_PATH}:$(ocamlfind query z3)"
$ ocaml setup.ml -build...
```
